package helpers

func Init() []Biodata {
	biodata := []Biodata{
		{},
		{
			Nama:      "Charles Prabowo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Maulana Dwi Wahyudi",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Musthafa Kamal Faishal",
			Alamat:    "Semarang",
			Pekerjaan: "Mahasiswa",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Widodo Saputra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Andreas Dimas Christanto",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Erza Fahmi Fasya",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Wahyu Tricahyo Mulyo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Rocky Prabowo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Alief Ahmad Azies",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ahmad Faozan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Reagent",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Cris Limpar",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Rivaldo Juliano",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Edwin Kevin Kondo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Firmando Parulian Situmorang",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Pandu Pramudya",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Iqbal Hadi Purnomo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Donny Marcius",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dimas Kunto Aji",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Richardo Hans Martin",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Hilman Maulana Anhar",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Arfan Fadillah",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Surya Ferary Nainggolan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Arif Sutriyono",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ricky Defian Saputra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Muhammad Naufa Dzulfiqar",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Andromedha Anjar Wasari",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Rohmat Syamsul Huda",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Habib Abdurrasyid",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Renaldi Nurcahya Aditama",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Paulus Josianlie",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Teddy Adhitya",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Naufal Ikhsan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Kevin Joshwadi Malau",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Mursyied Qathafi",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Josua Williams Hasiholan Tampubolon",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Joy Sepindo Lumbantobing",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Repi Maulana Risyan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Falih Fauzan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Haafidz Nurul Salim",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Edy Pratamajaya",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Wildan Taufiq Abdul Aziz",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ahmad Fadhil",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Randy Nasuta",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Pradika Fajar Rillo Pambudi",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Muhammad Afif Ma'ruf",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Irham Sahbana",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dwi Satria Patra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Azka Nurhuda",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Irfan Arsyad",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Toto Setiawan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ari Johand Lomo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Laurensius Yuda Wicaksono Nugroho",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Regy Saputra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ryan Novary Pradana",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ahmad Siddiq",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ryan Nala Kusuma",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Wildan Arif Pradana",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
	}

	return biodata
}
